id: CounterCraft-Test
version: -1
name: CounterCraft-Test
starttaskid: "0"
tasks:
  "0":
    id: "0"
    taskid: a2bdb758-0c1a-4f50-8477-324569c2d08b
    type: start
    task:
      id: a2bdb758-0c1a-4f50-8477-324569c2d08b
      version: -1
      name: ""
      iscommand: false
      brand: ""
    nexttasks:
      '#none#':
      - "1"
    separatecontext: false
    view: |-
      {
        "position": {
          "x": 450,
          "y": 50
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
  "1":
    id: "1"
    taskid: ff67bf81-ef40-42e6-8b19-987e3fca60d8
    type: regular
    task:
      id: ff67bf81-ef40-42e6-8b19-987e3fca60d8
      version: -1
      name: DeleteContext
      description: Delete field from context
      scriptName: DeleteContext
      type: regular
      iscommand: false
      brand: ""
    nexttasks:
      '#none#':
      - "7"
      - "2"
    scriptarguments:
      all:
        simple: "yes"
      index: {}
      key: {}
      keysToKeep: {}
      subplaybook: {}
    separatecontext: false
    view: |-
      {
        "position": {
          "x": 450,
          "y": 230
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
  "2":
    id: "2"
    taskid: c89a7c66-bc4e-41a4-8c8e-59af108e3296
    type: regular
    task:
      id: c89a7c66-bc4e-41a4-8c8e-59af108e3296
      version: -1
      name: countercraft-get-object
      description: Get information about an object (IoC)
      script: CounterCraft Deception Director|||countercraft-get-object
      type: regular
      iscommand: true
      brand: CounterCraft Deception Director
    nexttasks:
      '#none#':
      - "9"
    scriptarguments:
      value:
        simple: root
    separatecontext: false
    view: |-
      {
        "position": {
          "x": 1010,
          "y": 430
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
  "3":
    id: "3"
    taskid: fa7e55e8-b7ca-4e0f-893a-34333cdc0f01
    type: condition
    task:
      id: fa7e55e8-b7ca-4e0f-893a-34333cdc0f01
      version: -1
      name: Verify Command Results
      type: condition
      iscommand: false
      brand: ""
    nexttasks:
      "yes":
      - "4"
    separatecontext: false
    conditions:
    - label: "yes"
      condition:
      - - operator: isEqualString
          left:
            value:
              simple: CounterCraft.Campaign.[0].Name
            iscontext: true
          right:
            value:
              simple: Test Campaign
    view: |-
      {
        "position": {
          "x": 520,
          "y": 880
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
  "4":
    id: "4"
    taskid: 02fbb458-2db6-43ab-80f6-676b800524cc
    type: regular
    task:
      id: 02fbb458-2db6-43ab-80f6-676b800524cc
      version: -1
      name: closeInvestigation
      description: Close the current incident
      script: Builtin|||closeInvestigation
      type: regular
      iscommand: true
      brand: Builtin
    scriptarguments:
      assetid: {}
      closeNotes: {}
      closeReason: {}
      emailclassification: {}
      id:
        simple: ${incident.id}
      phishingsubtype: {}
    separatecontext: false
    view: |-
      {
        "position": {
          "x": 520,
          "y": 1140
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
  "5":
    id: "5"
    taskid: 1a865824-deb6-4c15-80b9-f762ee165921
    type: regular
    task:
      id: 1a865824-deb6-4c15-80b9-f762ee165921
      version: -1
      name: PrintContext
      description: Pretty-print the contents of the playbook context
      scriptName: PrintContext
      type: regular
      iscommand: false
      brand: ""
    scriptarguments:
      outputformat: {}
    separatecontext: false
    view: |-
      {
        "position": {
          "x": 730,
          "y": 660
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
  "6":
    id: "6"
    taskid: a0069954-8967-4d3f-8ee5-c940aad1cd79
    type: regular
    task:
      id: a0069954-8967-4d3f-8ee5-c940aad1cd79
      version: -1
      name: countercraft-list-campaigns
      description: 'List all deception campaigns '
      script: CounterCraft Deception Director|||countercraft-list-campaigns
      type: regular
      iscommand: true
      brand: CounterCraft Deception Director
    nexttasks:
      '#none#':
      - "3"
      - "8"
    scriptarguments:
      name:
        simple: Test Campaign
    separatecontext: false
    view: |-
      {
        "position": {
          "x": 230,
          "y": 660
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
  "7":
    id: "7"
    taskid: de19d47d-1955-48b8-82c3-3e617d92c405
    type: regular
    task:
      id: de19d47d-1955-48b8-82c3-3e617d92c405
      version: -1
      name: countercraft-create-campaign
      description: Create a new deception campaign
      script: CounterCraft Deception Director|||countercraft-create-campaign
      type: regular
      iscommand: true
      brand: CounterCraft Deception Director
    nexttasks:
      '#none#':
      - "6"
      - "5"
    scriptarguments:
      description:
        simple: Test Description
      name:
        simple: Test Campaign
    separatecontext: false
    view: |-
      {
        "position": {
          "x": 450,
          "y": 430
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
  "8":
    id: "8"
    taskid: 97588cc2-360c-4ff5-80e3-9f5b0a09c700
    type: regular
    task:
      id: 97588cc2-360c-4ff5-80e3-9f5b0a09c700
      version: -1
      name: PrintContext
      description: Pretty-print the contents of the playbook context
      scriptName: PrintContext
      type: regular
      iscommand: false
      brand: ""
    scriptarguments:
      outputformat: {}
    separatecontext: false
    view: |-
      {
        "position": {
          "x": 0,
          "y": 880
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
  "9":
    id: "9"
    taskid: ebc44c7f-1e4b-455c-81c1-be32ee16eb26
    type: regular
    task:
      id: ebc44c7f-1e4b-455c-81c1-be32ee16eb26
      version: -1
      name: PrintContext
      description: Pretty-print the contents of the playbook context
      scriptName: PrintContext
      type: regular
      iscommand: false
      brand: ""
    scriptarguments:
      outputformat: {}
    separatecontext: false
    view: |-
      {
        "position": {
          "x": 1180,
          "y": 660
        }
      }
    note: false
    timertriggers: []
    ignoreworker: false
view: |-
  {
    "linkLabelsPosition": {},
    "paper": {
      "dimensions": {
        "height": 1185,
        "width": 1560,
        "x": 0,
        "y": 50
      }
    }
  }
inputs: []
outputs: []
